module.exports.ERR_GAMESTARTED = 'ERR_GAMESTARTED';
module.exports.ERR_GAMENOTSTARTED = 'ERR_GAMENOTSTARTED';
module.exports.ERR_NOTENOUGHPLAYERS = 'ERR_NOTENOUGHPLAYERS';
module.exports.ERR_NOTYOURTURN = 'ERR_NOTYOURTURN';

module.exports.ERR_BADCALL = 'ERR_BADCALL';
module.exports.ERR_BADBLUFF = 'ERR_BADBLUFF';
